version: '3.9'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: lafteldb
      POSTGRES_USER: laftel
      POSTGRES_PASSWORD: laftel
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7.0

  web:
    build: .
    command: bash -c "python manage.py migrate && gunicorn app.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  celery:
    build: .
    command: celery -A app worker --loglevel=info
    volumes:
      - ./app:/app
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
